lib/hex_flora_web/router.ex
defmodule HexFloraWeb.Router do
  use HexFloraWeb, :router

  pipeline :browser do
    plug :put_root_layout, {HexFloraWeb.LayoutView, :root}
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", HexFloraWeb do
    pipe_through :browser

    get "/", PageController, :home
    get "/flora-of-the-hex", PageController, :flora
    get "/about-hexflora", PageController, :about
    get "/how-to-contribute", PageController, :contribute
    resources "/specimens", SpecimenController, only: [:show, :index]
    resources "/vegetation_types", VegetationTypeController, only: [:show, :index]
  end

  # Other scopes may use custom stacks.
  # scope "/api", HexFloraWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: HexFloraWeb.Telemetry
    end
  end
end

lib/hex_flora/application.ex
defmodule HexFlora.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    children = [
      # Start the Telemetry supervisor
      HexFloraWeb.Telemetry,
      # Start the PubSub system
      {Phoenix.PubSub, name: HexFlora.PubSub},
      # Start the Endpoint (http/https)
      HexFloraWeb.Endpoint
      # Start a worker by calling: HexFlora.Worker.start_link(arg)
      # {HexFlora.Worker, arg}
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: HexFlora.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    HexFloraWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/hex_flora/herbarium/specimen.ex
defmodule HexFlora.Herbarium.Specimen do
  defmodule Builder do
    @enforce_keys [:id, :name, :rank, :taxonomy, :body, :description]
    defstruct [:id, :name, :rank, :taxonomy, :body, :description, vegetation_type_ids: [], common_names: [], local_names: []]

    def build(filename, attrs, body) do
      id = filename |> Path.basename() |> Path.rootname()
      [description, body] = String.split(body, "<!-- read more -->", parts: 2)
      struct!(__MODULE__, [id: id, description: description, body: body] ++ Map.to_list(attrs))
    end
  end

  use NimblePublisher,
    build: Builder,
    from: Application.app_dir(:hex_flora, "priv/specimens/*.md"),
    as: :specimens,
    highlighters: []

  # The @specimens variable is first defined by NimblePublisher.
  # Let's further modify it by sorting all specimens.
  @specimens Enum.sort_by(@specimens, & &1.name)

  def list(), do: @specimens

  def list_by_vegetation_type_id(vegetation_type_id) do
    Enum.filter(list(), &(vegetation_type_id in &1.vegetation_type_ids))
  end

  def get_by_id!(id) do
    Enum.find(list(), &(&1.id == id))
  end
end

lib/hex_flora/herbarium/vegetation_type.ex
defmodule HexFlora.Herbarium.VegetationType do
  defmodule Builder do
    @enforce_keys [:id, :name, :has_image?, :body]
    defstruct [:id, :name, :has_image?, :body, :public?]

    def build(filename, attrs, body) do
      id = filename |> Path.basename() |> Path.rootname()
      struct!(__MODULE__, [id: id, body: body] ++ Map.to_list(attrs))
    end
  end

  use NimblePublisher,
    build: Builder,
    from: Application.app_dir(:hex_flora, "priv/vegetation_types/*.md"),
    as: :vegetation_types,
    highlighters: []

  # The @vegetation_types variable is first defined by NimblePublisher.
  # Let's further modify it.
  @vegetation_types Enum.sort_by(@vegetation_types, & &1.name)
  @vegetation_types Enum.filter(@vegetation_types, & &1.public?)

  def list, do: @vegetation_types

  def get_by_id!(id) do
    Enum.find(list(), &(&1.id == id))
  end
end

lib/mix/tasks/hf.gen.spec.ex
defmodule Mix.Tasks.Hf.Gen.Spec do
  @shortdoc "Generates a specimen markdown document."

  @moduledoc """
  Generates a specimen markdown document.
      mix hf.gen.spec Apocynaceae Stapelia grandiflora
  The first argument is the family name followed by the genus
  and the species.

  Overall, this generator will add the following files to `priv/herbarium`:
    * a markdown file in `priv/herbarium/genus_species.md`
    * it will expect an image at `assets/static/images/genus_species.jpg`
  """
  use Mix.Task

  @keys [:family, :genus, :species]

  @doc false
  def run(args) do
    bindings =
      @keys
      |> Enum.zip(args)

    rendered = EEx.eval_file("priv/templates/specimen.md", bindings)
    File.write("priv/specimens/#{String.downcase(bindings[:genus])}_#{bindings[:species]}.md", rendered)
  end
end

lib/mix/tasks/hf.gen.veg.ex
defmodule Mix.Tasks.Hf.Gen.Veg do
  @shortdoc "Generates a vegetation type markdown document."

  @moduledoc """
  Generates a vegetation type markdown document.
      mix hf.gen.veg South Hex Sandstone Fynbos
  The first argument is vegetation type name.

  Overall, this generator will add the following files to `priv/vegetation_types`:
    * a markdown file in `priv/vegetation_types/name.md`
    * it will expect an image at `assets/static/images/name.jpg`
  """
  use Mix.Task

  @keys [:name]

  @doc false
  def run(args) do
    bindings =
      @keys
      |> Enum.zip(args)

    id = bindings[:name] |> String.downcase() |> String.replace(" ", "_")

    rendered = EEx.eval_file("priv/templates/vegetation_type.md", bindings)
    File.write("priv/vegetation_types/#{id}.md", rendered)
  end
end

lib/hex_flora_web/controllers/page_controller.ex
defmodule HexFloraWeb.PageController do
  use HexFloraWeb, :controller

  def home(conn, _params) do
    conn
    |> put_layout(false)
    |> render("home.html")
  end

  def flora(conn, _params) do
    conn
    |> render("flora.html")
  end

  def about(conn, _params) do
    conn
    |> render("about.html")
  end

  def contribute(conn, _params) do
    conn
    |> render("contribute.html")
  end
end

lib/hex_flora_web/controllers/specimen_controller.ex
defmodule HexFloraWeb.SpecimenController do
  use HexFloraWeb, :controller

  alias HexFlora.Herbarium.Specimen

  def index(conn, _params) do
    render(conn, "index.html", specimens: Specimen.list())
  end

  def show(conn, %{"id" => id}) do
    render(conn, "show.html", specimen: Specimen.get_by_id!(id))
  end
end

lib/hex_flora_web/controllers/vegetation_type_controller.ex
defmodule HexFloraWeb.VegetationTypeController do
  use HexFloraWeb, :controller

  alias HexFlora.Herbarium.VegetationType

  def index(conn, _params) do
    render(conn, "index.html", vegetation_types: VegetationType.list())
  end

  def show(conn, %{"id" => id}) do
    conn
    |> assign(:specimens, HexFlora.Herbarium.Specimen.list_by_vegetation_type_id(id))
    |> render("show.html", vegetation_type: VegetationType.get_by_id!(id))
  end
end

lib/hex_flora_web/views/error_view.ex
defmodule HexFloraWeb.ErrorView do
  use HexFloraWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/hex_flora_web/views/layout_view.ex
defmodule HexFloraWeb.LayoutView do
  use HexFloraWeb, :view
end

lib/hex_flora_web/views/page_view.ex
defmodule HexFloraWeb.PageView do
  use HexFloraWeb, :view
end

lib/hex_flora_web/views/specimen_view.ex
defmodule HexFloraWeb.SpecimenView do
  use HexFloraWeb, :view
end

lib/hex_flora_web/views/vegetation_type_view.ex
defmodule HexFloraWeb.VegetationTypeView do
  use HexFloraWeb, :view
end

lib/hex_flora_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>HexFlora</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/assets/app.css") %>"/>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=New+Tegomin&display=swap" rel="stylesheet">
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/assets/app.js") %>"></script>
  </head>
  <body class="d-flex flex-column h-100 overflow-auto">
    <div class="container">
    <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container">
      <a href="/" class="navbar-brand d-flex align-items-center mb-3 mb-md-0 me-md-auto text-decoration-none">
        <%# svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg %>
        <span class="" style="font-family: 'New Tegomin', serif;">HexFlora</span>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav ms-auto mb-2 mb-md-0">
        <li class="nav-item"><a href="<%= Routes.specimen_path(@conn, :index) %>" class="nav-link <%= if "specimens" in @conn.path_info do %>active<% end %>">Specimens</a></li>
        <li class="nav-item"><a href="<%= Routes.vegetation_type_path(@conn, :index) %>" class="nav-link <%= if "vegetation_types" in @conn.path_info do %>active<% end %>">Vegetation Types</a></li>
        <li class="nav-item">
          <a href="<%= Routes.page_path(@conn, :about) %>" class="nav-link <%= if @conn.private.phoenix_action == :about do %>active<% end %>">About</a>
        </li>
        <li class="nav-item">
          <a href="<%= Routes.page_path(@conn, :contribute) %>" class="nav-link <%= if @conn.private.phoenix_action == :contribute do %>active<% end %>">Contribute</a>
        </li>
      </ul>
        <%# form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form %>
      </div>
    </div>
  </nav>
    </header>
    </div>
    <main role="main" class="container h-auto" style="padding-top: 60px; padding-bottom: 104px;">
      <%= @inner_content %>
    </main>
    <%#footer class="footer mt-auto py-3 bg-light fixed-bottom">
      <div class="container text-center">
        <span class="text-muted">Licensed under the <a href="https://creativecommons.org/licenses/by/3.0/za">Creative Commons Attribution 3.0 (South Africa) License</a>.</span>
      </div>
    </footer %>
  </body>
</html>

lib/hex_flora_web/templates/layout/app.html.heex
<main role="main" class="container h-auto" style="padding-top: 60px; padding-bottom: 104px;">
  <%= @inner_content %>
</main>

lib/hex_flora_web/templates/layout/live.html.heex
<main role="main" class="container h-auto" style="padding-top: 60px; padding-bottom: 104px;">
  <%= @inner_content %>
</main>

lib/hex_flora_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>HexFlora</title>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=New+Tegomin&display=swap" rel="stylesheet">
    <%= csrf_meta_tag() %>
    <script phx-track-static defer type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body class="d-flex flex-column h-100 overflow-auto">
    <div class="container">
    <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container">
      <a href="/" class="navbar-brand d-flex align-items-center mb-3 mb-md-0 me-md-auto text-decoration-none">
        <%# svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg %>
        <span class="" style="font-family: 'New Tegomin', serif;">HexFlora</span>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav ms-auto mb-2 mb-md-0">
        <li class="nav-item"><a href={Routes.specimen_path(@conn, :index)} class={["nav-link"] ++ [(if "specimens" in @conn.path_info, do: "active", else: "")]}>Specimens</a></li>
        <li class="nav-item"><a href={Routes.vegetation_type_path(@conn, :index)} class={["nav-link"] ++ [(if "vegetation_types" in @conn.path_info, do: "active", else: "")]}>Vegetation Types</a></li>
        <li class="nav-item">
          <a href={Routes.page_path(@conn, :about)} class={["nav-link"] ++ [(if @conn.private.phoenix_action == :about, do: "active", else: "")]}>About</a>
        </li>
        <li class="nav-item">
          <a href={Routes.page_path(@conn, :contribute)} class={["nav-link"] ++ [(if @conn.private.phoenix_action == :contribute, do: "active", else: "")]}>Contribute</a>
        </li>
      </ul>
      </div>
    </div>
  </nav>
    </header>
    </div>
    <main role="main" class="container h-auto" style="padding-top: 60px; padding-bottom: 104px;">
      <%= @inner_content %>
    </main>
  </body>
</html>

lib/hex_flora_web/templates/page/home.html.eex
<!DOCTYPE html>
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="google-site-verification" content="QdGPaPRyHTiO-aX0STB6YoYLJrT0HpKtWTWdW_cdjdE"/>
    <title>HexFlora</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/assets/app.css") %>"/>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=New+Tegomin&display=swap" rel="stylesheet">
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body class="d-flex flex-column h-100">

<!-- Begin page content -->
<main class="flex-shrink-0 container">
    <section class="row">
      <div class="px-4 pt-5 my-5 text-center border-bottom">
        <h1 class="display-4" style="font-family: 'New Tegomin', serif;">HexFlora</h1>
        <div class="col-lg-6 mx-auto">
          <p class="lead mb-4">HexFlora is an online Herbarium, dedicated to the flora of the Hex River Valley.
          Browse through the specimens and vegetation types or read more about the project.</p>
          <div class="d-grid gap-2 d-sm-flex justify-content-sm-center mb-5">
            <a class="btn btn-primary btn-lg px-4 me-sm-3" href="<%= Routes.specimen_path(@conn, :index) %>">Browse specimens</a>
            <a class="btn btn-outline-secondary btn-lg px-4 me-sm-3" href="<%= Routes.vegetation_type_path(@conn, :index) %>">Browse vegetation types</a>
            <a class="btn btn-outline-secondary btn-lg px-4" href="<%= Routes.page_path(@conn, :about) %>">Read more</a>
          </div>
        </div>
      </div>
    </section>
</main>



<%#footer class="footer mt-auto py-3 bg-light">
  <div class="container text-center">
    <span class="text-muted">Please report issues <a href="https://github.com/palm86/hex_flora/issues/new">here</a>. This content is licensed under the <a href="https://creativecommons.org/licenses/by/3.0/za">Creative Commons Attribution 3.0 (South Africa) License</a>.</span>
  </div>
</footer %>
</body>

</html>

lib/hex_flora_web/templates/specimen/index.html.eex
<h1 class="display-4">All specimens</h1>
<h1><small class="text-muted">Showing <%= length(@specimens) %> of <%= length(@specimens) %></small></h1>

<div class="album py-5">
  <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4 g-4">
    <%= for specimen <- @specimens do %>
    <div class="col">
      <div class="card shadow-sm h-100">
        <img src="<%= Routes.static_url(@conn, "/images/" <> specimen.id <> ".jpg") %>" alt="<%= specimen.name %>">

        <div class="card-body">
          <h5 class="card-title"><%= if specimen.rank in [:species, :genus] do %>
            <i><%= link specimen.name, to: Routes.specimen_path(@conn, :show, specimen)%></i>
            <% else %>
            <%= link specimen.name, to: Routes.specimen_path(@conn, :show, specimen)%>
            <% end %>
            <p class="card-text"><small class="text-muted"><%= Enum.join(specimen.common_names, ", ") %></small></p>
          </h5>
          <div class="d-flex justify-content-between align-items-center">
            <small class="text-muted"><%= specimen.taxonomy[:family] %></small>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

lib/hex_flora_web/templates/specimen/show.html.eex
<%= link "← All specimens", to: Routes.specimen_path(@conn, :index)%>

<div class="mb-3">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="<%= Routes.static_url(@conn, "/images/" <> @specimen.id <> ".jpg") %>" alt="<%= @specimen.name %>" class="float-start img-thumbnail">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h1 class="card-title display-4"><%= if @specimen.rank in [:species, :genus] do %>
        <i><%= @specimen.name %></i>
        <% else %>
        <%= @specimen.name %>
        <% end %>
        </h1>
        <h2>
        <small class="card-text"><small class="text-muted"><%= Enum.join(@specimen.common_names, ", ") %></small>
        </h2>
        <p class="card-text lead"><%= raw @specimen.description %></p>
        <p class="card-text"><%= raw @specimen.body %></p>
      </div>
    </div>
  </div>
</div>

lib/hex_flora_web/templates/vegetation_type/index.html.eex
<section class="row">
  <article class="col">
    <h1 class="display-4">Vegetation Types</h1>
    <p class="lead">The Hex River Valley is a floral transition zone between Fynbos, Renosterveld
    and Karoo vegetation types. It is also a geological transition zone between the Cape Fold
    Mountains and the buttes (koppies) and mesas (table-like hills) of the Karoo.</p>

    <div class="row wx-auto row-cols-1 row-cols-sm-3">
      <figure class="figure col">
        <img src="<%= Routes.static_url(@conn, "/images/fynbos.jpg") %>" class="figure-img img-thumbnail" alt="Fynbos">
        <figcaption class="figure-caption">A <b>Fynbos</b> landscape, featuring a common sunshine conebush (<i>Leucadendron salignum</i>).</figcaption>
      </figure>

      <figure class="figure col">
        <img src="<%= Routes.static_url(@conn, "/images/renosterveld.jpg") %>" class="figure-img img-thumbnail" alt="Fynbos">
        <figcaption class="figure-caption">A <b>Renosterveld</b> landscape, featuring a renosterbos (<i>Dicerothamnus rhinocerotis</i>).</figcaption>
      </figure>

      <figure class="figure col">
        <img src="<%= Routes.static_url(@conn, "/images/robertson_karoo.jpg") %>" class="figure-img img-thumbnail" alt="Karoo">
        <figcaption class="figure-caption">A <b>Karoo</b> landscape, featuring a botterboom (<i>Tylecodon paniculatus</i>).</figcaption>
      </figure>
    </div>

    <h3>Fynbos</h3>

    <p>Fynbos is a biome that is endemic to the Cape region. The word literally translates to "fine bush". Fynbos
    species tend to be highly specialized and adapted to their habitats. They thrive in sandy, nutrient-poor,
    acidic soils (hence the local name "Suurveld" or acidic field), and occur in winter rainfall areas. They are extremely
    well-adapted to the dry hot summer months. They often have small, hairy leaves that allow them to reflect the sun and
    minimize water loss. Many Fynbos species rely on fire to stimulate germination. Ants also play an important role in depositing seeds
    underground.</p>

    <h3>Renosterveld</h3>

    <p>Renosterveld is a vegetation type that is strictly part of the Fynbos biome, but prefers more nutrient rich, loamy
    soils and therefore lacks several characteristic Fynbos species such as proteas, heaths, restios, and hardleaves. Instead,
    Renosterveld is dominated by the renosterbos, a hardy pale unpalatable shrub. Other notable species such as snowbushes,
    karees, sand olives, and tentfigs, some of which also occur in Fynbos, accompany the renosterbos.</p>

    <h3>Karoo</h3>

    <p>The De Doorns Karoo (often in a mosaic with Renosterveld) is a vegetation type of the Succulent Karoo biome. It is sometimes
    treated as synonymous with Worcester Karoo or Robertson Karoo and is endemic to the Breede River Valley. It is a winter rainfall
    area on the rain shadow side of the Hex River Mountains receiving much less rain than Fynbos. The area is rich in succulents (aloes,
    spurges, butterbushes, babboon cabbages, succulent geraniums), geophytes (numerous bulbous and cormous species), seasonal undergrowth
    (daisies), and Karoobossies (kraalbushes, gumbushes and snowbushes).</p>

    <h3>Vegetation types</h3>

    <p>The broad Fynbos, Renosterveld, and Karoo themes are further broken down into vegetation types, a dozen or so of which flow together
    in the Hex River Valley.</p>

      <div class="row wx-auto row-cols-1 row-cols-sm-1">
      <figure class="figure col">
        <img src="<%= Routes.static_url(@conn, "/images/hex_veg.jpg") %>" class="figure-img img-thumbnail" alt="Vegetation type map">
        <figcaption class="figure-caption">A map of the Hex River Valley with vegetation types overlaid. Source: Helme, N. A. 2007.</figcaption>
      </figure>
    </div>

    <div class="album py-5">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4 g-4">
        <%= for vegetation_type <- @vegetation_types do %>
        <div class="col">
          <div class="card shadow-sm h-100">
            <%=if vegetation_type.has_image? do %><img src="<%= Routes.static_url(@conn, "/images/" <> vegetation_type.id <> ".jpg") %>" alt="<%= vegetation_type.name %>"><% end %>

            <div class="card-body">
              <h5 class="card-title">
                <%= link vegetation_type.name, to: Routes.vegetation_type_path(@conn, :show, vegetation_type)%>
              </h5>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>

    <h3>References</h3>

    <ul>
      <li>Helme, N. A. 2007. Botanical report: Fine scale vegetation mapping in the Upper Breede River Valley. Report for CapeNature, as part of the C.A.P.E. programme.</li>
      <li>Mucina, L., Rutherford, M.C. 2006. The vegetation of South Africa, Lesotho and Swaziland. Strelitzia 19.</li>
      <li>Manning, J., 2018. Field Guide to Fynbos</li>
      <li>https://en.wikipedia.org/wiki/Renosterveld</li>
      <li>https://en.wikipedia.org/wiki/Robertson_Karoo</li>
      <li>http://pza.sanbi.org/vegetation (and related links)</li>
    </ul>

  </article>
</section>

lib/hex_flora_web/templates/vegetation_type/show.html.eex
<%= link "← All vegetation_types", to: Routes.vegetation_type_path(@conn, :index)%>

<div class="mb-3">
  <div class="row g-0">
    <div class="col-md-4">
      <%= if @vegetation_type.has_image? do %><img src="<%= Routes.static_url(@conn, "/images/" <> @vegetation_type.id <> ".jpg") %>" alt="<%= @vegetation_type.name %>" class="float-start img-thumbnail"><% end %>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h1 class="card-title display-4"><%= @vegetation_type.name %></h1>
        <p class="card-text"><%= raw @vegetation_type.body %></p>
      </div>
    </div>
  </div>
</div>

<h3>Species in this vegetation type</h3>

<div class="album py-5">
  <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4 g-4">
    <%= for specimen <- @specimens do %>
    <div class="col">
      <div class="card shadow-sm h-100">
        <img src="<%= Routes.static_url(@conn, "/images/" <> specimen.id <> ".jpg") %>" alt="<%= specimen.name %>">

        <div class="card-body">
          <h5 class="card-title"><%= if specimen.rank in [:species, :genus] do %>
            <i><%= link specimen.name, to: Routes.specimen_path(@conn, :show, specimen)%></i>
            <% else %>
            <%= link specimen.name, to: Routes.specimen_path(@conn, :show, specimen)%>
            <% end %>
            <p class="card-text"><small class="text-muted"><%= Enum.join(specimen.common_names, ", ") %></small></p>
          </h5>
          <div class="d-flex justify-content-between align-items-center">
            <small class="text-muted"><%= specimen.taxonomy[:family] %></small>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>